version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - nesjs-network
    volumes:
      - ./src/server/db:/var/lib/postgresql/data
      - ./src/server/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432

  prod:
    depends_on:
      - db
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: src/server/Dockerfile
    env_file:
      - .env.production
    links:
      - db
    command: npm run start:prod
    ports:
      - 8080:8080
    networks:
      - nesjs-network
    volumes:
      - ./src/server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
networks:
  nesjs-network:
