version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - nesjs-network
    volumes:
      - ./src/server/db:/var/lib/postgresql/data
      - ./src/server/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432

  react-client:
    depends_on:
      - backend
    networks:
      - nesjs-network
    build:
      dockerfile: ./src/react-client/Dockerfile.dev
      context: ./src/react-client
    image: react-client-dev:1.0.0
    env_file:
      - .env.development
    container_name: react_client_dev
    ports:
      - 3000:3000
    environment:
      BACKEND_URL: backend

  backend:
    depends_on:
      - db
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./src/server/
      dockerfile: ./src/server/Dockerfile
      target: development
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      PORT: 8080
#    command: npm run start:debug
    ports:
      - 8080:8080
    networks:
      - nesjs-network
    volumes:
      - ./src/server:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

networks:
  nesjs-network:
