
FROM node:12-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install
RUN npm install -g @angular/cli@7.3.9

COPY . .

RUN ng build --prod --output-path=dist



FROM nginx:1.16.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
